-- =============================================================================
-- GymApp — exercise library (SuperPhysique catalogue, grouped by muscle group)
-- =============================================================================
-- Adds every exercise below to EVERY existing user's personal library.
-- Idempotent: re-running only inserts what is missing.
-- Run in the Supabase dashboard: SQL Editor -> New query -> paste -> Run.
-- New sign-ups get the same list automatically (seeded from src/data/exercises.js).

insert into public.exercises (user_id, name, category)
select u.id, e.name, e.category
from auth.users u
cross join (values
  ('Dips prise large buste penché', 'Pectoraux'),
  ('Développé assis à la machine convergente', 'Pectoraux'),
  ('Développé couché avec haltères', 'Pectoraux'),
  ('Développé couché à la barre', 'Pectoraux'),
  ('Développé couché à la machine', 'Pectoraux'),
  ('Développé couché à la machine convergente', 'Pectoraux'),
  ('Développé décliné avec haltères', 'Pectoraux'),
  ('Développé décliné à la barre', 'Pectoraux'),
  ('Développé incliné avec haltères', 'Pectoraux'),
  ('Développé incliné à la barre', 'Pectoraux'),
  ('Développé incliné à la machine convergente', 'Pectoraux'),
  ('Pompes prise large au sol', 'Pectoraux'),
  ('Pull over avec barre ou haltère', 'Pectoraux'),
  ('Pull over en travers d’un banc avec barre ou haltère', 'Pectoraux'),
  ('Pull over à la poulie basse', 'Pectoraux'),
  ('Écarté couché avec haltères', 'Pectoraux'),
  ('Écarté décliné avec haltères', 'Pectoraux'),
  ('Écarté incliné avec haltères', 'Pectoraux'),
  ('Écarté pectoraux à la machine', 'Pectoraux'),
  ('Écarté à la poulie vis à vis basse', 'Pectoraux'),
  ('Écarté à la poulie vis à vis haute', 'Pectoraux'),
  ('Pull over assis à la machine', 'Dos'),
  ('Pull over debout à la poulie haute', 'Dos'),
  ('Traction prise large devant à la barre fixe', 'Dos'),
  ('Traction prise large nuque à la barre fixe', 'Dos'),
  ('Traction prise neutre à la barre fixe', 'Dos'),
  ('Traction prise serrée en pronation à la barre fixe', 'Dos'),
  ('Traction prise supination cambré à la barre fixe', 'Dos'),
  ('Traction à la machine', 'Dos'),
  ('Traction à la machine convergente', 'Dos'),
  ('Traction à la poulie haute devant', 'Dos'),
  ('Traction à la poulie haute nuque', 'Dos'),
  ('Traction à la poulie haute prise neutre', 'Dos'),
  ('Traction à la poulie haute prise serrée en pronation', 'Dos'),
  ('Traction à la poulie haute prise supination', 'Dos'),
  ('Traction à la poulie haute à un bras', 'Dos'),
  ('Rowing assis à la machine', 'Trapèzes'),
  ('Rowing assis à la poulie basse en pronation', 'Trapèzes'),
  ('Rowing assis à la poulie basse en supination', 'Trapèzes'),
  ('Rowing assis à la poulie basse prise neutre', 'Trapèzes'),
  ('Rowing assis à la poulie basse à un bras', 'Trapèzes'),
  ('Rowing barre allongé sur banc', 'Trapèzes'),
  ('Rowing barre buste penché en pronation', 'Trapèzes'),
  ('Rowing barre en supination', 'Trapèzes'),
  ('Rowing barre à la Yates en pronation', 'Trapèzes'),
  ('Rowing barre à la Yates en supination', 'Trapèzes'),
  ('Rowing debout prise serrée avec barre', 'Trapèzes'),
  ('Rowing inversé au poids de corps', 'Trapèzes'),
  ('Rowing à la poulie basse sur banc incliné', 'Trapèzes'),
  ('Rowing à la poulie haute en prise neutre', 'Trapèzes'),
  ('Rowing à la poulie haute en pronation', 'Trapèzes'),
  ('Rowing à la poulie haute en supination', 'Trapèzes'),
  ('Rowing à la poulie haute à un bras', 'Trapèzes'),
  ('Rowing à la T-bar', 'Trapèzes'),
  ('Rowing à la T-bar à la machine', 'Trapèzes'),
  ('Rowing à un bras avec haltère', 'Trapèzes'),
  ('Rowing à un bras à la machine', 'Trapèzes'),
  ('Rowing à un bras à la poulie basse', 'Trapèzes'),
  ('Shrug avec barre', 'Trapèzes'),
  ('Shrug avec haltères', 'Trapèzes'),
  ('Shrug à la machine', 'Trapèzes'),
  ('Shrug à la machine convergente', 'Trapèzes'),
  ('Shrug à la machine à mollets', 'Trapèzes'),
  ('Shrug à la poulie', 'Trapèzes'),
  ('Soulevé de terre partiel avec barre', 'Trapèzes'),
  ('Développé inversé au poids de corps', 'Épaules'),
  ('Développé militaire avec barre', 'Épaules'),
  ('Développé nuque avec barre', 'Épaules'),
  ('Développé épaules Arnold avec haltères', 'Épaules'),
  ('Développé épaules avec haltères', 'Épaules'),
  ('Développé épaules à la machine', 'Épaules'),
  ('Développé épaules à la machine convergente', 'Épaules'),
  ('L-Fly allongé à la poulie basse', 'Épaules'),
  ('L-Fly assis à la poulie basse', 'Épaules'),
  ('L-Fly avec haltère', 'Épaules'),
  ('L-Fly debout à la poulie', 'Épaules'),
  ('Oiseau avec haltères', 'Épaules'),
  ('Oiseau sur banc incliné avec haltères', 'Épaules'),
  ('Oiseau à la machine', 'Épaules'),
  ('Oiseau à la poulie basse', 'Épaules'),
  ('Oiseau à la poulie haute', 'Épaules'),
  ('Oiseau à un bras allongé', 'Épaules'),
  ('Oiseau/Rowing avec haltères', 'Épaules'),
  ('Pompes indiennes', 'Épaules'),
  ('Rotation externe debout avec barre', 'Épaules'),
  ('Rotation interne allongé à la poulie basse', 'Épaules'),
  ('Rotation interne assis à la poulie basse', 'Épaules'),
  ('Rotation interne avec haltère', 'Épaules'),
  ('Rotation interne debout à la poulie', 'Épaules'),
  ('Rowing assis à la machine coudes ouverts', 'Épaules'),
  ('Rowing assis à la poulie basse coudes ouverts', 'Épaules'),
  ('Rowing barre coudes ouverts', 'Épaules'),
  ('Rowing debout prise large avec barre', 'Épaules'),
  ('Rowing debout à la poulie basse', 'Épaules'),
  ('Rowing à la poulie basse sur banc incliné coudes ouverts', 'Épaules'),
  ('Rowing à la poulie haute sur banc incliné coudes ouverts', 'Épaules'),
  ('Rowing à la T-bar coudes ouverts', 'Épaules'),
  ('Élévation frontale avec haltères', 'Épaules'),
  ('Élévation frontale avec une barre', 'Épaules'),
  ('Élévation frontale sur banc incliné avec barre ou haltères', 'Épaules'),
  ('Élévation frontale à la poulie', 'Épaules'),
  ('Élévation latérale avec haltères', 'Épaules'),
  ('Élévation latérale à la machine', 'Épaules'),
  ('Élévation latérale à la poulie', 'Épaules'),
  ('Élévation latérale à un bras penché sur le côté', 'Épaules'),
  ('Élévation latérale à un bras sur banc incliné', 'Épaules'),
  ('Curl allongé à la poulie basse', 'Biceps'),
  ('Curl allongé à la poulie haute', 'Biceps'),
  ('Curl araignée avec barre', 'Biceps'),
  ('Curl au pupitre avec barre', 'Biceps'),
  ('Curl au pupitre à la machine', 'Biceps'),
  ('Curl au pupitre à la poulie', 'Biceps'),
  ('Curl avec haltères', 'Biceps'),
  ('Curl concentré avec haltère', 'Biceps'),
  ('Curl incliné avec haltères', 'Biceps'),
  ('Curl marteau avec haltères', 'Biceps'),
  ('Curl marteau en travers avec haltères', 'Biceps'),
  ('Curl marteau à la poulie basse', 'Biceps'),
  ('Curl à la barre', 'Biceps'),
  ('Curl à la poulie basse', 'Biceps'),
  ('Curl à la poulie vis à vis', 'Biceps'),
  ('Traction prise supination non cambré à la barre fixe', 'Biceps'),
  ('Barre au front allongé à la poulie basse', 'Triceps'),
  ('Barre au front triceps avec barre ou haltères', 'Triceps'),
  ('Dips entre deux bancs', 'Triceps'),
  ('Dips prise serrée', 'Triceps'),
  ('Dips à la machine', 'Triceps'),
  ('Développé couché prise serrée à la barre', 'Triceps'),
  ('Extension des triceps bras à 180 degrés avec barre ou haltères', 'Triceps'),
  ('Extension des triceps buste penché à la poulie haute', 'Triceps'),
  ('Extension des triceps contre un mur au poids de corps', 'Triceps'),
  ('Extension des triceps à la machine', 'Triceps'),
  ('Extension des triceps à la poulie avec la corde', 'Triceps'),
  ('Extension des triceps à la poulie coudes écartés', 'Triceps'),
  ('Extension des triceps à la poulie en pronation', 'Triceps'),
  ('Extension des triceps à la poulie en supination', 'Triceps'),
  ('Extension des triceps à la poulie haute à genoux', 'Triceps'),
  ('Extension des triceps à la poulie à un bras', 'Triceps'),
  ('Extension nuque avec barre ou haltère', 'Triceps'),
  ('Extension nuque à la poulie', 'Triceps'),
  ('Extension nuque à un bras avec haltère', 'Triceps'),
  ('Kickback avec haltère', 'Triceps'),
  ('Kickback à la poulie', 'Triceps'),
  ('Magic tRYCeps avec barre ou haltère', 'Triceps'),
  ('Pompes prise serrée au sol', 'Triceps'),
  ('Pull over Press avec barre ou haltère', 'Triceps'),
  ('Tate Press avec haltères', 'Triceps'),
  ('Tate Press à un bras avec haltère', 'Triceps'),
  ('Bobine Andrieux - Extension', 'Avant-bras'),
  ('Bobine Andrieux - Flexion', 'Avant-bras'),
  ('Curl inversé allongé à la poulie basse', 'Avant-bras'),
  ('Curl inversé allongé à la poulie haute', 'Avant-bras'),
  ('Curl inversé au pupitre avec barre', 'Avant-bras'),
  ('Curl inversé au pupitre à la poulie', 'Avant-bras'),
  ('Curl inversé avec barre', 'Avant-bras'),
  ('Curl inversé à la poulie', 'Avant-bras'),
  ('Extension des poignets avec barre', 'Avant-bras'),
  ('Flexion des poignets avec barre', 'Avant-bras'),
  ('Adducteurs assis à la machine', 'Quadriceps'),
  ('Adducteurs à la machine', 'Quadriceps'),
  ('Adducteurs à la poulie', 'Quadriceps'),
  ('Fente latérale avec barre', 'Quadriceps'),
  ('Flexion de la hanche à une jambe à la machine', 'Quadriceps'),
  ('Gobelet Squat avec haltère', 'Quadriceps'),
  ('Hack squat avec une barre', 'Quadriceps'),
  ('Hack squat à la machine', 'Quadriceps'),
  ('Leg extension allongé à la machine', 'Quadriceps'),
  ('Leg extension assis à la machine', 'Quadriceps'),
  ('Montée sur banc avec barre ou haltères', 'Quadriceps'),
  ('Presse à cuisses allongé', 'Quadriceps'),
  ('Presse à cuisses assis', 'Quadriceps'),
  ('Presse à cuisses incliné', 'Quadriceps'),
  ('Relevé de buste au sol ou sur banc incliné', 'Quadriceps'),
  ('Relevé de genoux allongé au sol ou sur banc incliné', 'Quadriceps'),
  ('Relevé de genoux sur banc', 'Quadriceps'),
  ('Relevé de genoux suspendu à la barre fixe', 'Quadriceps'),
  ('Sissy squat', 'Quadriceps'),
  ('Sissy squat à la presse allongé', 'Quadriceps'),
  ('Squat avant avec barre', 'Quadriceps'),
  ('Squat avec barre derrière la nuque', 'Quadriceps'),
  ('Squat avec ceinture de lest', 'Quadriceps'),
  ('Squat avec haltères', 'Quadriceps'),
  ('Squat bulgare avec barre ou haltères', 'Quadriceps'),
  ('Squat indien', 'Quadriceps'),
  ('Squat sumo avec barre', 'Quadriceps'),
  ('Squat à la machine', 'Quadriceps'),
  ('Squat à la machine à mollets', 'Quadriceps'),
  ('Squat à la Smith machine', 'Quadriceps'),
  ('Squat à une jambe au poids de corps', 'Quadriceps'),
  ('Extension au banc à lombaires à 45 degrés', 'Ischio-jambiers'),
  ('Extension au banc à lombaires à 90 degrés', 'Ischio-jambiers'),
  ('Glute Ham Raise au banc', 'Ischio-jambiers'),
  ('Good Morning avec barre', 'Ischio-jambiers'),
  ('Leg curl allongé à la machine', 'Ischio-jambiers'),
  ('Leg curl assis à la machine', 'Ischio-jambiers'),
  ('Leg curl debout à une jambe à la machine', 'Ischio-jambiers'),
  ('Leg curl debout à une jambe à la poulie', 'Ischio-jambiers'),
  ('Soulevé de terre jambes tendues avec barre ou haltères', 'Ischio-jambiers'),
  ('Soulevé de terre jambes tendues à la poulie', 'Ischio-jambiers'),
  ('Abducteurs allongé avec lest cheville', 'Fessiers'),
  ('Abducteurs assis à la machine', 'Fessiers'),
  ('Abducteurs à la machine', 'Fessiers'),
  ('Abducteurs à la poulie', 'Fessiers'),
  ('Extension de la hanche à la machine', 'Fessiers'),
  ('Extension inversé à la machine', 'Fessiers'),
  ('Fente arrière glissée avec Valslide', 'Fessiers'),
  ('Fente avec barre', 'Fessiers'),
  ('Fente en marchant avec barre ou haltères', 'Fessiers'),
  ('Fente en reculant avec barre ou haltères', 'Fessiers'),
  ('Fente à la Smith machine', 'Fessiers'),
  ('Hip thrust à la barre', 'Fessiers'),
  ('Soulevé de terre avec barre', 'Fessiers'),
  ('Soulevé de terre sumo avec barre', 'Fessiers'),
  ('Chameau à la machine', 'Mollets'),
  ('Mollets assis jambes tendues à la machine', 'Mollets'),
  ('Mollets assis à la machine', 'Mollets'),
  ('Mollets debout à la machine', 'Mollets'),
  ('Mollets debout à une jambe avec haltère', 'Mollets'),
  ('Mollets à la presse à cuisses', 'Mollets'),
  ('Crunch abdominaux au sol', 'Abdominaux'),
  ('Crunch abdominaux avec l’Abmat', 'Abdominaux'),
  ('Crunch abdominaux avec rotation au sol', 'Abdominaux'),
  ('Crunch abdominaux sur la Swiss Ball', 'Abdominaux'),
  ('Crunch abdominaux à la machine', 'Abdominaux'),
  ('Crunch oblique au sol', 'Abdominaux'),
  ('Crunch à la poulie haute', 'Abdominaux'),
  ('Drapeau du dragon', 'Abdominaux'),
  ('Enroulement de bassin au sol', 'Abdominaux'),
  ('Enroulement de bassin au sol avec l’Abmat', 'Abdominaux'),
  ('Enroulement de bassin suspendu à la barre fixe', 'Abdominaux'),
  ('Flexion latérale avec haltère', 'Abdominaux'),
  ('Gainage abdominal frontal', 'Abdominaux'),
  ('Gainage abdominal oblique', 'Abdominaux'),
  ('Obliques avec l’Abmat', 'Abdominaux'),
  ('Obliques sur banc à lombaires', 'Abdominaux'),
  ('Obliques sur la Swiss Ball', 'Abdominaux'),
  ('Obliques suspendu à la barre fixe', 'Abdominaux'),
  ('Rotation debout avec balais', 'Abdominaux'),
  ('Rotation à la machine', 'Abdominaux'),
  ('Vacuum', 'Abdominaux'),
  ('Enroulement/Déroulement au banc à lombaires', 'Lombaires'),
  ('Superman au sol', 'Lombaires')
) as e(name, category)
on conflict (user_id, name) do nothing;

-- Check counts per muscle group for your account:
--   select category, count(*) from public.exercises
--   where user_id = auth.uid() group by category order by count(*) desc;
